### ISSUE TITLE
How do you set a user's thumbnail with Graph API 2.0?

### ISSUE THREAD

**Issue by SharePointRadi** [AzureADSamples/ConsoleApp-GraphAPI-DotNet#12]
Should one use User.SetExtendedProperty? 1.2 had this?

**Comment by dkershaw10** [comment]
Here's a little code snippet that worked for me:
                FileStream fileStream = new FileStream(@"<JPG FILE PATH>", FileMode.Open, FileAccess.Read); 
                try
                {
                    userToBeAdded.ThumbnailPhoto.UploadAsync((Stream) fileStream, "application/image").Wait();
                    Console.WriteLine("\nUser {0} was updated with a thumbnailphoto", userToBeAdded.DisplayName);
                }
                catch (Exception e)
                {
                    Console.WriteLine("\nError Updating the user {0} {1}", e.Message,
                        e.InnerException != null ? e.InnerException.Message : "");
                }
