### ISSUE TITLE
How to remove user from Role? Please help..

### ISSUE THREAD

**Issue by belaie** [AzureADSamples/ConsoleApp-GraphAPI-DotNet#14]
https://msdn.microsoft.com/en-us/library/azure/jj134103.aspx

"Directory roles cannot be added or deleted using the Graph API. Updates are supported on the members navigation property only. Both add and remove are supported on this property."

According to this article, it is possible to add and remove the members navigation property of the role. I have tested Add user to role  works. but  Remove user from role does not work.

Code sample please?

**Comment by dkershaw10** [comment]
We'll take a look at this and get back to you.  It might be related to a similar issue around deleting app role assignments.

**Comment by dkershaw10** [comment]
T
