### ISSUE TITLE
How to get a user token without prompting the user to enter credentials

### ISSUE THREAD

**Issue by aramkoukia** [AzureADSamples/ConsoleApp-GraphAPI-DotNet#15]
I need to know how to get a user Graph token without prompting the user to enter credentials in the browser window. any ideas?

**Comment by dkershaw10** [comment]
Sorry for the late response.  Please see http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/ for some details.  NOTE this should be used only for the key scenarios that Vittorio outlines in the blog post.
